# Disable watchdog
nowatchdog

# Disable zswap for zram
zswap.enabled=0

# Disable kernel timer check
no_timer_check

# Fix crashing on some AMD GPUs 
amdgpu.dcdebugmask=0x12

# Requirements for VMs
iommu=soft
# amd_iommu=off

# Better compability with some faulty ACPI
acpi_osi="Windows 2022"

# DONT ENABLE IF UNINFORMED.  
# Forcibly disable PCIe ASPM.
# pcie_aspm=off
# pcie_port_pm=off

# Disable crypto self-tests
# cryptomgr.notests

# Limit processor to maximum C-state
# processor.max_cstate=0

# Poll forces a polling idle loop that can slightly improve the performance of waking up a idle CPU
# but will use a lot of power and make the system run hot. Not recommended.
# idle=nomwait

# Apparmor
# lsm=landlock,lockdown,yama,integrity,apparmor,bpf

# Do you trust the CPU hardware random number generator?
# random.trust_cpu=on

# iomem=relaxed