# VULNERABILITY FIX
# disable vulnerable protocols
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
# disable usb-storage driver
blacklist usb-storage
# disable builtin firewire
blacklist firewire-core
# disable builtin camera
blacklist uvcvideo

# PERFORMANCE
# disable watchdog driver
blacklist sp5100_tco

# UTILITY
# fn mode on some keyboard
options hid_apple fnmode=2 iso_layout=0