#!/bin/sh
xrdb -merge ${XDG_CONFIG_HOME}/Xresources
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export XDG_SESSION_TYPE=x11
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

exec dbus-launch openbox-session
